FROM mirror.gcr.io/library/node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM mirror.gcr.io/library/node:20-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3001

COPY --from=deps /app/node_modules ./node_modules
COPY backend ./backend
COPY package*.json ./

EXPOSE 3001
CMD ["node", "backend/index.js"]
